In [159]:
import numpy as np
import pandas as pd

In [160]:
print(np.__version__)

1.18.1


In [161]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [162]:
print(a.size)
print(a.itemsize)
print(a.nbytes)
print(a.size*a.itemsize)


10
8
80
80


In [163]:
np.info(np.abs)

absolute(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Calculate the absolute value element-wise.

``np.abs`` is a shorthand for this function.

Parameters
----------
x : array_like
    Input array.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``, locations within it where the condition is False will
    remain unin

In [164]:
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [165]:
print(np.arange(10))
print(np.arange(1,10,2))
print(np.arange(10,20))

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[10 11 12 13 14 15 16 17 18 19]


In [166]:
a=np.arange(1,10)
print(a[::-1])


[9 8 7 6 5 4 3 2 1]


In [167]:
a=np.arange(0,9).reshape((3,3))
a


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [168]:
a=np.array([1,2,3,40,0,0,0])
print(np.nonzero(a>1))


(array([1, 2, 3], dtype=int64),)


In [169]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [170]:
a=np.random.randint(1,50,100).reshape((10,10))
print(a)
print(a.max())
a.min()

[[31 14  2 38  3 31 18 24 45 35]
 [ 8  7 30  9 20 32 13 19 37 21]
 [29 33 47  2 38  9 17  2  5 16]
 [36 39 41 35 13  6 45 22 34 35]
 [35 37 49 34 33  7 36 23 49 10]
 [37 29 46 38 49 17  9 24  5 44]
 [13 17 12  1  4 37 11 21 28 26]
 [45  6 39 31 38 15 24 40 31 31]
 [21 42 14 43 28 22 18 38 42 36]
 [ 4 36 47 45 25 15  7 31 19 27]]
49


1

In [171]:
a=np.random.random(30)
a.mean()


0.4978753705256765

In [172]:
array = np.array([[1, 1],[2,2]])
ndarray=np.pad(array,((1,1)),"edge") 
 
print(array)
print(ndarray)

# np.info(np.pad)


[[1 1]
 [2 2]]
[[1 1 1 1]
 [1 1 1 1]
 [2 2 2 2]
 [2 2 2 2]]


In [173]:
np.equal(np.nan,np.nan)


False

In [174]:
a=np.arange(9).reshape((3,3))
np.diag(a,k=1)
x=[1,2,3]
np.diag(np.diag(a))

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

In [175]:
a=np.arange(10)
a[::2]

array([0, 2, 4, 6, 8])

In [177]:
a=np.random.randint(1,9,9).reshape(3,3)
print(a)
b=np.argmax(a)
print(b)
np.unravel_index(b,a.shape)

[[7 7 6]
 [7 1 6]
 [8 8 7]]
6


(2, 0)

In [184]:
a=np.array([[0,1],[1,0]])
print(a)
np.tile(a,(4,4))

[[0 1]
 [1 0]]


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [188]:
a=np.random.random((5,5))
a=(a-np.mean(a))/(np.std(a))
a

array([[-1.39088937, -0.36840128,  0.25569867,  1.37797702, -1.63441392],
       [ 0.24765818, -1.12108363, -0.15557901,  0.23647895, -1.6449774 ],
       [-1.54540147,  1.06609338,  0.37990889,  0.7722741 ,  0.20607164],
       [ 1.21523545,  1.16640294,  0.06725807,  0.47938362, -1.02047519],
       [ 1.85455226,  0.26808705, -1.29328417, -0.16540657,  0.74683178]])

In [198]:
a=np.arange(12).reshape(3,4)
b=np.random.randint(1,30,12).reshape(4,3)
c=np.dot(a,b)
c

array([[155, 135, 116],
       [475, 423, 436],
       [795, 711, 756]])

In [201]:
a=np.arange(12).reshape(3,4)
a[(a>3)&(a<10)]=-1
a



array([[ 0,  1,  2,  3],
       [-1, -1, -1, -1],
       [-1, -1, 10, 11]])

In [206]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [212]:
a=np.random.random(9)
np.around(a,decimals=4)

array([0.2663, 0.8405, 0.7293, 0.113 , 0.3492, 0.4143, 0.6329, 0.4645,
       0.1221])

In [249]:
a=np.random.randint(1,10,10)

b=np.random.randint(1,10,10)
print(a)
print(b)
c=np.intersect1d(a,b)
d=np.union1d(a,b)
print(c,d)

[8 8 6 3 3 5 9 6 5 3]
[3 5 4 8 1 7 1 7 4 7]
[3 5 8] [1 3 4 5 6 7 8 9]


In [260]:
c=np.datetime64("today","D")+np.timedelta64(12,"D")
c

numpy.datetime64('2020-02-27')